name: Build Snail IDE for desktop

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build-and-deploy:
    runs-on: ${{ matrix.os }}
    permissions: write-all

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: checkout the repo
        uses: actions/checkout@v3

      - name: clone sn
        run: |
          git config --global core.compression 0
          git clone --depth 1 https://github.com/Snail-IDE/snail-ide.github.io nobuildapp
          cd nobuildapp
          git fetch --unshallow
          git pull --all
          cd ..


      - name: get pnpm
        run: npm install -g pnpm@v6

      - name: build sn
        run: |
          cd nobuildapp
          pnpm i --shamefully-hoist --force
          npx webpack --bail
          cd ..
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      - name: copy build to /app
        run: |
          mkdir app
          cp -r nobuildapp/build/* app/

      - name: build electron app
        run: |
          pnpm i
          pnpm run publish "always"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
